### ISSUE TITLE
repo cleanup

### ISSUE THREAD

**Issue by fagoatse** [jpd002/Play--CodeGen#16]
Hi, been wondering if there's any reason to keep armv7 and x86_32 recompilers in 2017? Do they, by any chance, generate better/faster code then their 64bit equivalents?

**Comment by jpd002** [comment]
Not really, they're just there to allow CodeGen to work with more devices. armv7 is probably less important nowadays, but x86_32 is still useful for Android x86 devices (most of which don't support 64-bit AFAIK). They don't incur too much overhead to maintain, so, I don't have plans to remove support for those.
